const locations=[{name:'Sapporo',short:'Sapporo',coords:[43.0618,141.3545],nights:'2 nights'},{name:'Noboribetsu',short:'Noboribetsu',coords:[42.4525,141.179],nights:'1 night'},{name:'Hakodate',short:'Hakodate',coords:[41.7687,140.7291],nights:'2 nights'},{name:'Sendai',short:'Sendai',coords:[38.2682,140.8694],nights:'2 nights'},{name:'Tokyo',short:'Tokyo',coords:[35.6762,139.6503],nights:'10 nights'},{name:'Nikko',short:'Nikko',coords:[36.7199,139.6982],nights:'1 night'}];
const stays=[['24–25 Oct','Sapporo · 2 nights'],['26 Oct','Noboribetsu · 1 night · private bath'],['27–28 Oct','Hakodate · 2 nights'],['29–30 Oct','Sendai · 2 nights'],['31 Oct–1 Nov','Tokyo · 2 nights · Halloween'],['2 Nov','Nikko · 1 night · private bath'],['3–10 Nov','Tokyo · 8 nights']].map(([dates,text])=>({dates,text}));
const place=(name,type,note,query,coords)=>({name,type,note,query,coords});
const rows=[
['23','Fri 23 Oct','In the air','IB281 Madrid → Narita · depart 12:30','north',0,'Outbound',[place('IB281','transit','Arrive Narita 09:30 next day.','Iberia Madrid airport')]],
['24','Sat 24 Oct','Sapporo','Narita → Peach → New Chitose → Susukino','north',0,'Arrival',[place('Peach NRT → CTS','transit','Book 15:00 or later; checked baggage required.','Narita International Airport Terminal 1'),place('Soup curry or miso ramen','eat','Easy first dinner near the station.','Sapporo Station')]],
['25','Sun 25 Oct','Sapporo','Nijo Market · ginkgo avenue · Mt Moiwa night view','north',1,'⭐ Unmissable',[place('Nijo Market','visit','07:30 · kaisendon, salmon and ikura.','Nijo Market Sapporo',[43.058,141.356]),place('GARAKU soup curry','eat','Lunch · expect a Sunday queue.','GARAKU Sapporo'),place('Hokkaido University Ginkgo Avenue','visit','Free, flat, central walk.','Hokkaido University Ginkgo Avenue',[43.077,141.34]),place('Mt Moiwa','visit','20:30 · tram + shuttle for city lights.','Mount Moiwa Observatory Sapporo',[43.024,141.323]),place('Sapporo Beer Museum','optional','Free exhibition if energy allows.','Sapporo Beer Museum',[43.071,141.367])]],
['26','Mon 26 Oct','Noboribetsu 🛁','Jigokudani · footbath · reserved private bath','north',1,'Private bath + Book',[place('Jigokudani','visit','Steaming volcanic valley boardwalk.','Jigokudani Noboribetsu',[42.506,141.145]),place('Oyunumagawa Footbath','optional','Free natural footbath.','Oyunumagawa Natural Footbath Noboribetsu',[42.503,141.153]),place('Noboribetsu Grand Hotel','book','Reserve the single ¥4,400 private bath.','Noboribetsu Grand Hotel',[42.494,141.142]),place('Onibi-no-Michi','visit','Illuminated boardwalk after dinner.','Onibi no Michi Noboribetsu',[42.505,141.145])]],
['27','Tue 27 Oct','Hakodate','Motomachi · Mt Hakodate sunset by summit bus','north',1,'⭐ Unmissable + Deadline',[place('Motomachi','visit','Foreign quarter and cobbled slopes.','Motomachi Hakodate',[41.765,140.711]),place('Mt Hakodate Summit Bus','visit','15:50 onward · bus, not ropeway.','Mount Hakodate Observatory',[41.759,140.704]),place('Ajisai shio ramen','eat','Arrival dinner in station building.','Ajisai Hakodate',[41.773,140.726]),place('Leave Noboribetsu by 10:15','note','Only comfortable connection is Hokuto 8 at 11:00.','Noboribetsu Station')]],
['28','Wed 28 Oct','Hakodate','Morning Market · Goryokaku · Lucky Pierrot · slow day','north',0,'Slow day',[place('Hakodate Morning Market','visit','06:30 · try ika-tsuri live squid.','Hakodate Morning Market',[41.774,140.727]),place('Goryokaku Tower','visit','Star fort from above.','Goryokaku Tower',[41.796,140.757]),place('Lucky Pierrot','eat','Hakodate-only Chinese Chicken Burger.','Lucky Pierrot Hakodate'),place('Kanemori Red Brick Warehouses','optional','Free waterfront wander.','Kanemori Red Brick Warehouse',[41.768,140.716])]],
['29','Thu 29 Oct','Sendai','Hayabusa south · arcades · gyutan + Bunka Yokocho','north',0,'Rail pass',[place('Hayabusa 18 → Sendai','transit','10:53 · oversized baggage reservation required.','Sendai Station',[38.26,140.882]),place('Sendai Asaichi','visit','Browse and snack after arrival.','Sendai Asaichi',[38.258,140.88]),place('Gyutan at Aji-Tasuke','eat','18:00 · heritage pick, walk-in queue.','Aji Tasuke Honten Sendai',[38.262,140.87]),place('Bunka Yokocho','visit','Tiny local bars, cash and Miyagi sake.','Bunka Yokocho Sendai',[38.262,140.87])]],
['30','Fri 30 Oct','Sendai','Matsushima · cruise · Zuiganji · anago','north',1,'Day trip',[place('Matsushima Bay Cruise','visit','Bay cruise and island views.','Matsushima Bay Cruise',[38.37,141.06]),place('Zuiganji','visit','Cedar-lined temple approach.','Zuiganji Temple',[38.37,141.06]),place('Anago lunch','eat','Choose anago, not oyster huts.','Matsushima anago restaurant'),place('Entsuin / Fukuurajima','optional','Only if timing and energy allow.','Entsuin Temple Matsushima')]],
['31','Sat 31 Oct','Tokyo 🎃','Asaichi breakfast · Ikebukuro cosplay · Halloween to 05:00','tokyo',1,'Halloween',[place('Asaichi breakfast','eat','Early market breakfast before 09:31 Hayabusa.','Sendai Asaichi',[38.258,140.88]),place('Ikebukuro cosplay festival','visit','Festival, Otome Road and costume browsing.','Ikebukuro Otome Road',[35.729,139.719]),place('Kōenji izakaya crawl','eat','Shape B route, no taxi.','Koenji Station',[35.706,139.649]),place('WARP Shinjuku','optional','Late-night club option.','WARP Shinjuku',[35.693,139.703]),place('Costume at Don Quijote','book','Buy on the day.','Don Quijote Ikebukuro')]],
['01','Sun 1 Nov','Tokyo','Recovery day — nothing scheduled','tokyo',0,'Recovery',[place('No fixed plans','optional','Sleep, laundry and a gentle walk only.','Tokyo Station')]],
['02','Mon 2 Nov','Nikko 🛁','Midday arrival · spa day · Kanmangafuchi','tokyo',1,'Private bath',[place('Kanmangafuchi Abyss','visit','Flat riverside walk with stone Jizo.','Kanmangafuchi Abyss Nikko',[36.758,139.592]),place('Hotel Casual Euro','book','Every room has its own open-air bath.','Hotel Casual Euro Nikko',[36.75,139.594]),place('08:20 taxi for Toshogu','book','Reserve tonight for the 09:00 opening.','Nikko Toshogu Shrine',[36.758,139.598])]],
['03','Tue 3 Nov','Tokyo','Toshogu 09:00 · Taiyuinbyo · Tobu express back','tokyo',1,'⭐ Unmissable + Book',[place('Toshogu Shrine','visit','09:00 opening; arrive by taxi.','Nikko Toshogu Shrine',[36.758,139.598]),place('Taiyuinbyo + Rinnoji','visit','Temple cluster after Toshogu.','Taiyuinbyo Nikko'),place('Yuba lunch','eat','Call ahead; listings conflict.','Yubatei Masudaya Nikko'),place('Tobu limited express','book','Reserve evening return before travel.','Tobu Nikko Station',[36.75,139.625])]],
['04','Wed 4 Nov','Tokyo · Monzen-Nakacho','Deep Fukagawa · fire ritual · Edo museum · fukagawa-meshi','tokyo',0,'Tokyo base',[place('Fukagawa Fudo-do','visit','Fire ritual in old neighbourhood.','Fukagawa Fudo-do Tokyo',[35.671,139.797]),place('Fukagawa Edo Museum','visit','Immersive reconstruction of Edo life.','Fukagawa Edo Museum',[35.684,139.8]),place('Fukagawa-meshi','eat','Local clam rice specialty.','Monzen Nakacho Fukagawa meshi'),place('Tomioka Hachiman','optional','Shrine and shitamachi streets.','Tomioka Hachimangu',[35.671,139.796])]],
['05','Thu 5 Nov','Tokyo','Kamakura + Enoshima · Great Buddha · Enoden coast','tokyo',1,'⭐ Unmissable + Day trip',[place('Kamakura Great Buddha','visit','Morning visit.','Kamakura Daibutsu',[35.316,139.536]),place('Shirasu lunch','eat','Ask for raw nama-shirasu; boiled is reliable.','Kamakura shirasu restaurant'),place('Enoden coast','visit','Ride or walk the coast.','Enoshima Station',[35.31,139.487]),place('Enoshima','optional','Skip paid extras if keeping it cheap.','Enoshima',[35.299,139.481])]],
['06','Fri 6 Nov','Tokyo','Kappabashi · Kuramae · Edo kiriko · Jimbocho','tokyo',0,'Workshop + Book',[place('Kuramae','visit','Small workshops and craft shops.','Kuramae Tokyo',[35.704,139.79]),place('Kappabashi','visit','Kitchen tools and gyuto hunt.','Kappabashi Dougu Street',[35.713,139.789]),place('Edo kiriko workshop','book','Reserve; ¥7,260 confirmed.','Edo Kiriko workshop Tokyo'),place('Jimbocho','optional','Bookshops if there is room.','Jimbocho Tokyo',[35.696,139.758])]],
['07','Sat 7 Nov','Tokyo','Map Camera · Shimokitazawa · Kitasenju','tokyo',0,'Shopping',[place('Map Camera','visit','Start here for used camera gear.','Map Camera Shinjuku',[35.691,139.701]),place('Shimokitazawa','visit','Vintage clothing and music streets.','Shimokitazawa Tokyo',[35.661,139.668]),place('Kitasenju','optional','Local evening atmosphere.','Kitasenju Tokyo',[35.749,139.805]),place('Vintage izakaya','eat','Small counter dinner.','Kitasenju izakaya')]],
['08','Sun 8 Nov','Tokyo','Akabane daytime drinking · soft day','tokyo',0,'Soft day',[place('Akabane','visit','10:00 · old alleys and daytime drinking.','Akabane Tokyo',[35.778,139.72]),place('Akabane izakaya','eat','Standing bars and early counters.','Akabane Ichiban Gai'),place('Monzen-Nakacho','optional','Return early for a local dinner.','Monzen Nakacho Tokyo',[35.672,139.796])]],
['09','Mon 9 Nov','Tokyo','Indigo dyeing AM · teamLab Borderless PM','tokyo',1,'Workshop + Timed entry',[place('Wanariya indigo dyeing','book','10:00 · reservations required.','Wanariya Tokyo'),place('teamLab Borderless','book','14:00 · timed entry.','teamLab Borderless Azabudai',[35.661,139.739]),place('Azabudai lunch','eat','Keep lunch close to the timed entry.','Azabudai Hills Tokyo')]],
['10','Tue 10 Nov','Tokyo','Tsukiji outer market · depachika · pack','tokyo',0,'Last day',[place('Tsukiji Outer Market','visit','Morning grazing and food gifts.','Tsukiji Outer Market',[35.665,139.77]),place('Depachika','eat','Final snacks and gifts.','Nihombashi Mitsukoshi depachika'),place('Pack and ship luggage','book','Use takkyubin if needed.','Tokyo Station Yaesu South Exit',[35.681,139.767]),place('Last Monzen-Nakacho evening','optional','One final local izakaya.','Monzen Nakacho Tokyo',[35.672,139.796])]],
['11','Wed 11 Nov','Fly home','08:30 out · TYO-NRT bus · IB282 14:10','tokyo',0,'Outbound',[place('TYO-NRT bus','transit','¥1,500 pp from Tokyo Station.','TYO-NRT bus Tokyo Station',[35.681,139.767]),place('IB282 Narita 14:10','transit','Keep generous international check-in buffer.','Narita International Airport',[35.772,140.392])]]
];
const days=rows.map((r,i)=>({id:`day-${i}`,number:r[0],date:r[1],dateShort:r[1].split(' ').slice(1).join(' '),base:r[2],title:r[3],region:r[4],flag:!!r[5],tag:r[6],summary:r[3],places:r[7]}));
