import { useCallback, useEffect, useMemo, useRef, useState } from 'react';
import { MapContainer, Marker, Popup, Polyline, TileLayer, ZoomControl, useMap } from 'react-leaflet';
import L from 'leaflet';
import {
  ArrowLeft, ArrowRight, BedDouble, CalendarDays, Check, ChevronDown, CircleAlert, CircleHelp,
  Clock3, Coffee, ExternalLink, Filter, Footprints, Landmark, Map as MapIcon, Menu, Moon, Mountain,
  Navigation, Plane, Printer, Route, TrainFront, Utensils, X, Zap,
} from 'lucide-react';
import { baseCities, bookings, budgetCategories, budgetTotals, confirmedHotelTotalEUR, googleMapsUrl, openItems, stays, totalNights, tripDays } from '../data/trip';
import type { BookingState, ItemType, Place, TripDay } from '../types/trip';

const formatJPY = (amount: number) => `¥${amount.toLocaleString('en-US')}`;
const googleDirectionsUrl = (query: string) => `https://www.google.com/maps/dir/?api=1&destination=${encodeURIComponent(query)}&travelmode=transit`;
const itemLabel: Record<ItemType, string> = { sight: 'Sight', food: 'Food', optional: 'Optional', transit: 'Transit', stay: 'Stay', booking: 'Book / verify', note: 'Note' };
const itemGlyph: Record<ItemType, string> = { sight: '✦', food: '🍜', optional: '○', transit: '→', stay: '⌂', booking: '!', note: 'i' };
const itemIcon: Record<ItemType, typeof Landmark> = { sight: Landmark, food: Utensils, optional: CircleHelp, transit: TrainFront, stay: BedDouble, booking: Zap, note: CircleAlert };

function markerIcon(type: ItemType, active: boolean) {
  return L.divIcon({ className: `map-marker marker-${type}${active ? ' is-active' : ''}`, html: `<span aria-hidden="true">${itemGlyph[type]}</span>`, iconSize: [34, 34], iconAnchor: [17, 17], popupAnchor: [0, -17] });
}

function FitBounds({ points }: { points: [number, number][] }) {
  const map = useMap();
  useEffect(() => { if (points.length > 1) map.fitBounds(L.latLngBounds(points), { padding: [38, 38], maxZoom: 12 }); else if (points[0]) map.setView(points[0], 12); }, [map, points]);
  return null;
}

function MapResize() { const map = useMap(); useEffect(() => { const timer = window.setTimeout(() => map.invalidateSize(), 120); return () => window.clearTimeout(timer); }, [map]); return null; }

function MapSelection({ place }: { place?: Place }) {
  const map = useMap();
  useEffect(() => {
    if (place?.coordinates) map.flyTo(place.coordinates, Math.max(map.getZoom(), 13), { duration: 0.45 });
  }, [map, place]);
  return null;
}

function MapView({ selectedDay, selectedPlaceId, onSelectPlace, filter }: { selectedDay?: TripDay; selectedPlaceId?: string; onSelectPlace: (place: Place) => void; filter: ItemType | 'all' }) {
  const places = selectedDay?.places ?? [];
  const mappedPlaces = useMemo(() => places.filter((place) => place.coordinates && (filter === 'all' || place.type === filter)), [places, filter]);
  const points = useMemo(() => mappedPlaces.map((place) => place.coordinates!).filter(Boolean), [mappedPlaces]);
  const routePoints = useMemo(() => selectedDay ? places.map((place) => place.coordinates).filter((point): point is [number, number] => Boolean(point)) : baseCities.map((city) => city.coordinates), [selectedDay, places]);
  const selectedPlace = selectedDay?.places.find((place) => place.id === selectedPlaceId);
  return <MapContainer className="leaflet-map" center={[39.8, 138.2]} zoom={5} scrollWheelZoom zoomControl={false} keyboard aria-label={selectedDay ? `Interactive map of ${selectedDay.base} places` : 'Interactive map of Japan route'}>
    <TileLayer attribution='&copy; <a href="https://carto.com/attributions">CARTO</a> &copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a>' url="https://{s}.basemaps.cartocdn.com/rastertiles/voyager/{z}/{x}/{y}{r}.png" subdomains="abcd" maxZoom={19} />
    <ZoomControl position="bottomright" /><MapResize /><MapSelection place={selectedPlace} /><FitBounds points={selectedDay ? (points.length ? points : routePoints) : baseCities.map((city) => city.coordinates)} />
    <Polyline positions={routePoints} pathOptions={{ color: '#d7654d', weight: selectedDay ? 3 : 4, dashArray: selectedDay ? '8 8' : undefined, opacity: .85 }} />
    {!selectedDay && baseCities.map((city) => <Marker key={city.name} position={city.coordinates} icon={markerIcon('stay', false)}><Popup><strong>{city.name}</strong><br />{city.nights} nights in the route</Popup></Marker>)}
    {selectedDay && mappedPlaces.map((place) => <Marker key={place.id} position={place.coordinates!} title={`${place.startTime ? `${place.startTime} · ` : ''}${place.name}`} alt={`${itemLabel[place.type]}: ${place.name}`} icon={markerIcon(place.type, selectedPlaceId === place.id)} eventHandlers={{ click: () => onSelectPlace(place) }}><Popup><div className="map-popup"><span className={`type-chip type-${place.type}`}>{itemLabel[place.type]}</span>{place.startTime && <small className="map-popup-time">{place.startTime}{place.durationMinutes ? ` · ${place.durationMinutes} min` : ''}</small>}<strong>{place.name}</strong><p>{place.description}</p>{place.cuisine && <p className="map-popup-detail">{place.cuisine}{place.signature ? ` · ${place.signature}` : ''}{place.mealContext ? ` · ${place.mealContext}` : ''}</p>}{place.bookingState && place.bookingState !== 'not-needed' && <p className="map-popup-detail">Status: {place.bookingState}</p>}<div className="map-popup-links"><a href={googleMapsUrl(place.mapsQuery)} target="_blank" rel="noopener noreferrer">Place <ExternalLink size={13} /></a><a href={googleDirectionsUrl(place.mapsQuery)} target="_blank" rel="noopener noreferrer">Directions <Footprints size={13} /></a></div></div></Popup></Marker>)}
  </MapContainer>;
}

function Header({ onMenu }: { onMenu: () => void }) {
  return <header className="site-header"><a className="brand" href="/japan-2026-plan/" aria-label="Japan, slowly home"><span className="brand-mark">日</span><span>Japan,<br /><em>slowly</em></span></a><nav className="main-nav" aria-label="Main navigation"><a href="#overview">Overview</a><a href="#daily-plan">Daily plan</a><a href="#bookings">Bookings</a><a href="#budget">Budget</a><a href="#practical">Practical notes</a></nav><button className="menu-button" onClick={onMenu} aria-label="Open navigation"><Menu size={22} /></button></header>;
}

function Stat({ label, value, accent = false }: { label: string; value: string; accent?: boolean }) { return <div className={`stat${accent ? ' accent' : ''}`}><strong>{value}</strong><span>{label}</span></div>; }

function PlaceCard({ place, selected, onSelect }: { place: Place; selected: boolean; onSelect: () => void }) {
  const Icon = itemIcon[place.type];
  return <li className={`place-card${selected ? ' selected' : ''}${place.fallback ? ' fallback' : ''}`}>
    <button className="place-main" onClick={onSelect} aria-pressed={selected}><span className={`place-icon icon-${place.type}`}><Icon size={17} /></span><span className="place-copy"><strong>{place.name}</strong><span>{place.description}</span>{place.cuisine && <small>{place.cuisine}{place.signature ? ` · ${place.signature}` : ''}{place.mealContext ? ` · ${place.mealContext}` : ''}</small>}{place.travelNote && <small className="travel-note"><Navigation size={11} /> {place.travelNote}</small>}</span>{place.startTime && <time>{place.startTime}</time>}</button>
    <div className="place-meta">{place.role && <span className={`role-label role-${place.role}`}>{place.role}</span>}{place.bookingState && place.bookingState !== 'not-needed' && <span className={`status status-${place.bookingState}`}><span aria-hidden="true">{place.bookingState === 'booked' ? '✓' : '!'}</span> {place.bookingState}</span>}{place.priceBand && <span>{place.priceBand}</span>}{place.estimatedCostJPY && <span>{formatJPY(place.estimatedCostJPY)}</span>}<a href={googleMapsUrl(place.mapsQuery)} target="_blank" rel="noopener noreferrer" aria-label={`Open ${place.name} place details in Google Maps`}>Place <ExternalLink size={12} /></a><a href={googleDirectionsUrl(place.mapsQuery)} target="_blank" rel="noopener noreferrer" aria-label={`Get directions to ${place.name}`}>Directions <Footprints size={12} /></a></div>
    {place.verification !== 'confirmed' && <div className="verification"><CircleAlert size={13} /> {place.verification === 'verify-before-trip' ? 'Verify before the trip' : 'Research lead — check close to travel'}</div>}
  </li>;
}

function DayCard({ day, selected, onSelect }: { day: TripDay; selected: boolean; onSelect: () => void }) {
  const foodCount = day.places.filter((place) => place.type === 'food').length;
  return <article className={`day-card${selected ? ' selected' : ''}`} role="button" tabIndex={0} aria-pressed={selected} aria-label={`Open ${day.weekday} ${day.date}, ${day.title}, on the map and itinerary`} onClick={onSelect} onKeyDown={(event: React.KeyboardEvent<HTMLElement>) => { if (event.key === 'Enter' || event.key === ' ') { event.preventDefault(); onSelect(); } }}><div className="day-date"><span>{day.weekday}</span><strong>{new Date(`${day.date}T12:00:00`).getDate()}</strong><small>{new Date(`${day.date}T12:00:00`).toLocaleString('en-US', { month: 'short' })}</small></div><div className="day-card-body"><div className="card-topline"><span className="eyebrow">{day.base}</span>{day.keyDay && <span className="key-badge">Key day</span>}</div><h3>{day.title}</h3><p>{day.summary}</p><div className="day-card-tags"><span>{day.pacing}</span><span>{day.places.filter((place) => place.type === 'sight').length} sights</span>{foodCount > 0 && <span>{foodCount} food</span>}</div><span className="text-button">{selected ? 'Day focus open' : 'View map + itinerary'} <ArrowRight size={15} /></span></div></article>;
}

function SectionHeading({ eyebrow, title, children }: { eyebrow: string; title: string; children?: React.ReactNode }) { return <div className="section-heading"><div><span className="eyebrow">{eyebrow}</span><h2>{title}</h2></div>{children}</div>; }

function DayTimeline({ day, selectedPlaceId, onSelectPlace }: { day: TripDay; selectedPlaceId?: string; onSelectPlace: (place: Place) => void }) {
  const minutes = (time?: string) => time ? Number(time.split(':')[0]) * 60 + Number(time.split(':')[1]) : -1;
  const groups: { label: string; items: Place[] }[] = [{ label: 'Morning', items: day.places.filter((place) => minutes(place.startTime) >= 300 && minutes(place.startTime) < 720) }, { label: 'Midday', items: day.places.filter((place) => minutes(place.startTime) >= 720 && minutes(place.startTime) < 900) }, { label: 'Afternoon', items: day.places.filter((place) => minutes(place.startTime) >= 900 && minutes(place.startTime) < 1140) }, { label: 'Evening', items: day.places.filter((place) => minutes(place.startTime) >= 1140 && minutes(place.startTime) < 1380) }, { label: 'Late night', items: day.places.filter((place) => minutes(place.startTime) >= 1380 || (minutes(place.startTime) >= 0 && minutes(place.startTime) < 300)) }, { label: 'Flexible', items: day.places.filter((place) => !place.startTime) }].filter((group) => group.items.length);
  return <div className="day-timeline">{groups.map((group) => <section key={group.label} className="timeline-group"><h3>{group.label}</h3><ol>{group.items.map((place, index) => <li key={place.id} className="timeline-row"><div className="timeline-time">{place.startTime || '—'}<span>{index < group.items.length - 1 ? '↓' : ''}</span></div><div className="timeline-line"><span className={`timeline-dot dot-${place.type}`} /></div><PlaceCard place={place} selected={selectedPlaceId === place.id} onSelect={() => onSelectPlace(place)} /></li>)}</ol></section>)}</div>;
}

function DayDetail({ day, selectedPlaceId, onSelectPlace, onClose, onChangeDay, first, last, mobile }: { day: TripDay; selectedPlaceId?: string; onSelectPlace: (place: Place) => void; onClose: () => void; onChangeDay: (offset: number) => void; first: boolean; last: boolean; mobile: boolean }) {
  const dialogRef = useRef<HTMLElement>(null);
  useEffect(() => { if (!mobile) return; const previous = document.activeElement as HTMLElement | null; dialogRef.current?.focus(); const onKey = (event: KeyboardEvent) => { if (event.key === 'Escape') onClose(); if (event.key === 'Tab' && dialogRef.current) { const focusable = Array.from(dialogRef.current.querySelectorAll<HTMLElement>('button,a,[tabindex]:not([tabindex="-1"])')); if (focusable.length && (event.shiftKey ? document.activeElement === focusable[0] : document.activeElement === focusable[focusable.length - 1])) { event.preventDefault(); (event.shiftKey ? focusable[focusable.length - 1] : focusable[0]).focus(); } } }; document.addEventListener('keydown', onKey); return () => { document.removeEventListener('keydown', onKey); previous?.focus(); }; }, [mobile, onClose]);
  const go = day.places.filter((place) => place.type === 'sight'); const eat = day.places.filter((place) => place.type === 'food'); const optional = day.places.filter((place) => place.type === 'optional'); const book = day.places.filter((place) => place.type === 'booking' || place.bookingState === 'required' || place.bookingState === 'recommended');
  return <aside className={`day-detail${mobile ? ' mobile-dialog' : ''}`} role={mobile ? 'dialog' : 'complementary'} aria-modal={mobile || undefined} aria-labelledby="day-detail-title" tabIndex={-1} ref={dialogRef}><div className="detail-top"><div><span className="eyebrow">Day focus · {day.weekday} {new Date(`${day.date}T12:00:00`).toLocaleString('en-US', { month: 'short', day: 'numeric' })}</span><h2 id="day-detail-title">{day.title}</h2><p>{day.base} · <span className={`pace pace-${day.pacing}`}>{day.pacing} pace</span> · ¥{day.dailyEstimateJPY ? `${day.dailyEstimateJPY.low.toLocaleString()}–${day.dailyEstimateJPY.high.toLocaleString()}` : '—'} per day</p></div><button className="icon-button close-detail" onClick={onClose} aria-label="Close day focus"><X size={21} /></button></div><div className="detail-actions"><button className="secondary-button" onClick={() => onChangeDay(-1)} disabled={first}><ArrowLeft size={16} /> Previous</button><button className="secondary-button" onClick={() => onChangeDay(1)} disabled={last}>Next <ArrowRight size={16} /></button><button className="secondary-button print-day-button" onClick={() => window.print()}><Printer size={15} /> Print day</button></div><p className="season-note"><Moon size={15} /> {day.seasonNote}</p><div className="detail-map-heading"><strong>{day.base} map</strong><span>Tap a marker for the stop and map link</span></div><div className="detail-map-shell"><MapView selectedDay={day} selectedPlaceId={selectedPlaceId} onSelectPlace={onSelectPlace} filter="all" /></div><DayTimeline day={day} selectedPlaceId={selectedPlaceId} onSelectPlace={onSelectPlace} /><div className="detail-sections"><DetailPlaceSection title="Go · committed sights" places={go} selectedPlaceId={selectedPlaceId} onSelectPlace={onSelectPlace} /><DetailPlaceSection title="Eat · primary first" places={eat} selectedPlaceId={selectedPlaceId} onSelectPlace={onSelectPlace} /><DetailPlaceSection title="Optional · only if energy allows" places={optional} selectedPlaceId={selectedPlaceId} onSelectPlace={onSelectPlace} /><DetailPlaceSection title="Book / verify" places={book} selectedPlaceId={selectedPlaceId} onSelectPlace={onSelectPlace} /></div>{(day.tiredPlan || day.rainPlan) && <div className="contingency"><h3><Coffee size={16} /> Keep a plan B</h3>{day.tiredPlan && <p><strong>If tired:</strong> {day.tiredPlan}</p>}{day.rainPlan && <p><strong>If raining:</strong> {day.rainPlan}</p>}</div>}</aside>;
}

function DetailPlaceSection({ title, places, selectedPlaceId, onSelectPlace }: { title: string; places: Place[]; selectedPlaceId?: string; onSelectPlace: (place: Place) => void }) { if (!places.length) return null; return <section className="detail-place-section"><h3>{title}</h3><ul>{places.map((place) => <PlaceCard key={place.id} place={place} selected={selectedPlaceId === place.id} onSelect={() => onSelectPlace(place)} />)}</ul></section>; }

function BookingBoard({ onSelectDay }: { onSelectDay: (dayId?: string) => void }) { return <section id="bookings" className="section"><SectionHeading eyebrow="Action board" title="Book before it becomes urgent"><span className="section-count"><Zap size={16} /> {bookings.filter((booking) => booking.status !== 'booked').length} open · {bookings.filter((booking) => booking.priority === 'required').length} required</span></SectionHeading><div className="booking-list">{bookings.map((booking) => <article className={`booking-row priority-${booking.priority}`} key={booking.id}><div className="booking-priority"><span>{booking.priority}</span><strong>{booking.status === 'booked' ? <Check size={17} /> : <CircleAlert size={17} />}</strong></div><div className="booking-main"><h3>{booking.item}</h3><p>{booking.notes}</p><div className="booking-meta"><span><CalendarDays size={14} /> {booking.date}</span><span><Clock3 size={14} /> {booking.deadline}</span><span>{booking.destination}</span></div></div><div className="booking-cost">{booking.estimatedCostJPY ? formatJPY(booking.estimatedCostJPY) : 'TBD'}<button className="text-button" onClick={() => onSelectDay(booking.dayId)}>Open day <ArrowRight size={14} /></button></div></article>)}</div></section>; }

function AccommodationTimeline() { return <section className="section compact-section" id="stays"><SectionHeading eyebrow="Where we sleep" title="Seven stays, five bases"><span className="section-count"><Check size={16} /> {stays.filter((stay) => stay.status === 'booked').length} confirmed · €{confirmedHotelTotalEUR}</span></SectionHeading><div className="stay-grid">{stays.map((stay) => <article className={`stay-card${stay.conflict ? ' stay-conflict' : ''}`} key={stay.id}><div className="stay-marker"><BedDouble size={17} /></div><div><div className="stay-card-top"><span>{stay.dates}</span><span className={`status status-${stay.status}`}>{stay.conflict ? 'date conflict' : stay.status}</span></div><h3>{stay.city}</h3><p>{stay.property}{stay.privateBath ? ' · Private bath' : ''}</p><small>{stay.note}{stay.costEUR ? ` · €${stay.costEUR}` : ''}</small><a className="stay-map-link" href={googleMapsUrl(stay.property)} target="_blank" rel="noopener noreferrer">Open property in Google Maps <ExternalLink size={12} /></a></div></article>)}</div></section>; }

function BudgetPanel() { const max = Math.max(...budgetCategories.map((category) => category.centre)); return <section id="budget" className="section budget-section"><SectionHeading eyebrow="The envelope" title="A budget with honest edges" /><div className="budget-layout"><div className="budget-hero"><span className="eyebrow">Estimated total · excluding shopping</span><strong>{formatJPY(budgetTotals.low)} <em>→</em> {formatJPY(budgetTotals.high)}</strong><p>Centre estimate {formatJPY(budgetTotals.centre)} · {formatJPY(Math.round(budgetTotals.centre / 2))} per person. These are planning ranges, not live prices.</p><div className="budget-confirmed"><span><Check size={15} /> Confirmed hotels</span><strong>€{confirmedHotelTotalEUR}</strong></div><p className="budget-note">Hotel reservations are now confirmed in Booking.com. The remaining Tokyo stay is still outside this total.</p></div><div className="budget-breakdown">{budgetCategories.map((category) => <div className="budget-line" key={category.id}><div><span>{category.label}</span><small>{formatJPY(category.low)}–{formatJPY(category.high)}</small></div><div className="budget-bar"><i style={{ width: `${Math.max(10, category.centre / max * 100)}%` }} /></div>{category.note && <p>{category.note}</p>}</div>)}</div></div></section>; }

function OpenItemsPanel({ onSelectDay }: { onSelectDay: (dayId?: string) => void }) { return <section id="practical" className="section open-section"><div className="open-panel"><div className="open-intro"><span className="eyebrow">Before you go</span><strong>{openItems.length}</strong><h2>open decisions</h2><p>Small actions that protect the shape of the trip. The count is calculated from the itinerary data.</p></div><div className="open-list">{openItems.map((item) => <button className={`open-item priority-${item.priority}`} key={item.id} onClick={() => onSelectDay(item.relatedDate)}><span className="open-item-icon"><CircleAlert size={16} /></span><span><strong>{item.label}</strong><small>{item.action}</small></span><ArrowRight size={17} /></button>)}</div></div></section>; }

export function App() {
  const [selectedDayId, setSelectedDayId] = useState<string | undefined>(() => new URLSearchParams(window.location.search).get('day') || undefined);
  const [selectedPlaceId, setSelectedPlaceId] = useState<string | undefined>();
  const [filter, setFilter] = useState<'all' | 'key' | 'food' | 'culture' | 'nature' | 'booking' | 'light' | 'balanced' | 'full'>('all');
  const [mapFilter, setMapFilter] = useState<ItemType | 'all'>('all');
  const [mobileMenu, setMobileMenu] = useState(false);
  const [mobile, setMobile] = useState(() => window.matchMedia('(max-width: 767px)').matches);
  const selectedDay = tripDays.find((day) => day.id === selectedDayId);
  const selectedIndex = selectedDay ? tripDays.indexOf(selectedDay) : -1;
  useEffect(() => { const media = window.matchMedia('(max-width: 767px)'); const onChange = () => setMobile(media.matches); media.addEventListener('change', onChange); return () => media.removeEventListener('change', onChange); }, []);
  useEffect(() => { const onPop = () => setSelectedDayId(new URLSearchParams(window.location.search).get('day') || undefined); window.addEventListener('popstate', onPop); return () => window.removeEventListener('popstate', onPop); }, []);
  useEffect(() => { document.body.classList.toggle('modal-open', Boolean(selectedDay && mobile)); return () => document.body.classList.remove('modal-open'); }, [selectedDay, mobile]);
  const selectDay = useCallback((dayId?: string) => { if (!dayId) return; const url = new URL(window.location.href); url.searchParams.set('day', dayId); window.history.pushState({}, '', url); setSelectedDayId(dayId); setSelectedPlaceId(undefined); document.getElementById('daily-plan')?.scrollIntoView({ behavior: 'smooth', block: 'start' }); }, []);
  const closeDay = useCallback(() => { const url = new URL(window.location.href); url.searchParams.delete('day'); window.history.pushState({}, '', `${url.pathname}${url.search}${url.hash}`); setSelectedDayId(undefined); setSelectedPlaceId(undefined); }, []);
  const changeDay = useCallback((offset: number) => { const target = tripDays[selectedIndex + offset]; if (target) selectDay(target.id); }, [selectDay, selectedIndex]);
  const shownDays = useMemo(() => tripDays.filter((day) => filter === 'all' || (filter === 'key' ? day.keyDay : filter === 'food' ? day.places.some((place) => place.type === 'food') : filter === 'booking' ? day.places.some((place) => place.bookingState === 'required' || place.type === 'booking') : filter === 'culture' || filter === 'nature' ? day.tags.includes(filter) : day.pacing === filter)), [filter]);
  const selectPlace = useCallback((place: Place) => setSelectedPlaceId(place.id), []);
  const mappedSelectedPlaces = selectedDay?.places.filter((place) => place.coordinates && (mapFilter === 'all' || place.type === mapFilter)) ?? [];
  return <div className="app-shell"><Header onMenu={() => setMobileMenu((open) => !open)} />{mobileMenu && <div className="mobile-menu"><button onClick={() => setMobileMenu(false)} className="icon-button" aria-label="Close navigation"><X /></button>{['overview', 'daily-plan', 'bookings', 'budget', 'practical'].map((id) => <a href={`#${id}`} key={id} onClick={() => setMobileMenu(false)}>{id.replace('-', ' ')}</a>)}</div>}<main>
    <section className="hero" id="overview"><div className="hero-orbit orbit-one" /><div className="hero-orbit orbit-two" /><div className="hero-content"><span className="eyebrow">23 October — 11 November 2026 · two adults</span><h1>Japan,<br /><em>slowly.</em></h1><p className="hero-lede">A north-to-Tokyo autumn journey built around local food, direct rail days, a slow Nikko overnight and enough blank space to notice where you are.</p><div className="stats"><Stat label="nights" value={String(totalNights)} /><Stat label="bases" value={String(baseCities.length)} accent /><Stat label="hotel nights booked" value={String(stays.filter((stay) => stay.status === 'booked').reduce((sum, stay) => sum + stay.nights, 0))} /><Stat label="open actions" value={String(openItems.length)} /></div></div><div className="hero-stamp"><span>Route</span><strong>Hokkaido<br />to Tokyo</strong><Route size={30} /></div></section>
    <section className="section route-section"><SectionHeading eyebrow="The shape of it" title="North first, then deep Tokyo"><span className="route-note"><Route size={16} /> 5 bases · 20 days · 1 gentle arc</span></SectionHeading><div className="map-toolbar"><div className="map-legend"><span><i className="legend-dot dot-stay" /> Base stays</span><span><i className="legend-dot dot-sight" /> Day places</span><span><i className="legend-dot dot-food" /> Food</span></div>{selectedDay && <button className="secondary-button" onClick={closeDay}>Show whole route</button>}</div><div className="map-shell"><MapView selectedDay={selectedDay} selectedPlaceId={selectedPlaceId} onSelectPlace={selectPlace} filter={mapFilter} /><div className="map-overlay"><span>{selectedDay ? `${selectedDay.base} · ${mappedSelectedPlaces.length} mapped places` : 'Whole trip route'}</span><label><Filter size={13} /><span className="sr-only">Map filter</span><select value={mapFilter} onChange={(event) => setMapFilter(event.target.value as ItemType | 'all')}><option value="all">All layers</option><option value="sight">Sights</option><option value="food">Food</option><option value="optional">Optional</option><option value="transit">Transit</option><option value="stay">Stays</option><option value="booking">Bookings</option></select></label></div></div><div className="route-strip">{baseCities.map((city, index) => <div className="route-stop" key={city.name}><span>{String(index + 1).padStart(2, '0')}</span><strong>{city.name}</strong><small>{city.nights} {city.nights === 1 ? 'night' : 'nights'}</small></div>)}</div></section>
    <AccommodationTimeline />
    <section id="daily-plan" className="section daily-section"><SectionHeading eyebrow="Every day has a shape" title="The daily plan"><div className="filter-bar"><label htmlFor="day-filter">Show</label><select id="day-filter" value={filter} onChange={(event) => setFilter(event.target.value as typeof filter)}><option value="all">All 20 days</option><option value="key">Key days</option><option value="food">Food anchors</option><option value="culture">Culture</option><option value="nature">Nature</option><option value="booking">Booking attention</option><option value="light">Light pace</option><option value="balanced">Balanced pace</option><option value="full">Full pace</option></select></div></SectionHeading><div className="day-explorer-layout"><div className="day-list" aria-label="Daily itinerary">{shownDays.map((day) => <DayCard key={day.id} day={day} selected={selectedDayId === day.id} onSelect={() => selectDay(day.id)} />)}</div>{selectedDay && !mobile && <DayDetail day={selectedDay} selectedPlaceId={selectedPlaceId} onSelectPlace={selectPlace} onClose={closeDay} onChangeDay={changeDay} first={selectedIndex === 0} last={selectedIndex === tripDays.length - 1} mobile={false} />}</div></section>
    <section className="section key-section"><SectionHeading eyebrow="Do not miss" title="Key moments"><div className="section-count"><Zap size={16} /> {tripDays.filter((day) => day.keyDay).length} key days</div></SectionHeading><div className="moment-grid">{[{ icon: '🎃', title: 'Halloween in Tokyo', date: '31 Oct', text: 'Ikebukuro cosplay by day; Koenji after dark.' }, { icon: '✦', title: 'Nikko, then Tokyo', date: '2–3 Nov', text: 'Travel and settle in on day one; Shōgun-era Toshogu and nearby grounds the next morning.' }, { icon: '⛴', title: 'Matsushima', date: '30 Oct', text: 'Cruise, Zuiganji and anago by the bay.' }, { icon: '✺', title: 'Hands-on Tokyo', date: '6 + 9 Nov', text: 'Edo kiriko, indigo dyeing and teamLab.' }].map((moment) => <article key={moment.title}><span className="moment-icon">{moment.icon}</span><span className="eyebrow">{moment.date}</span><h3>{moment.title}</h3><p>{moment.text}</p></article>)}</div></section>
    <BookingBoard onSelectDay={selectDay} /><BudgetPanel /><OpenItemsPanel onSelectDay={selectDay} />
  </main><footer><span>Japan, slowly · planning document for two</span><a href="./LUNA_IMPLEMENTATION_PLAN.md">Source plan</a><span>October — November 2026</span></footer>{selectedDay && mobile && <><div className="dialog-backdrop" onClick={closeDay} /><DayDetail day={selectedDay} selectedPlaceId={selectedPlaceId} onSelectPlace={selectPlace} onClose={closeDay} onChangeDay={changeDay} first={selectedIndex === 0} last={selectedIndex === tripDays.length - 1} mobile /></>}</div>;
}
